spring:

  datasource:
    url: @mysql.url.prod@
    username: @mysql.username.prod@
    password: @mysql.password.prod@

    redis:
      database: 2
      sentinel:
        master: master6006
        node: @redis.host.prod@
        port: @redis.port.prod@
        password: @redis.password.prod@
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
